"""
Convert your CSV data files into JSON format for use with D3.js / Scrollama.

Run this once your CSVs are populated. It produces a single combined
JSON file with everything your scrollytelling site needs.

USAGE:
    python csv_to_json.py --data_dir data/ --output viz_data.json
"""

import argparse
import csv
import json
from pathlib import Path


def csv_to_records(csv_path):
    """Read a CSV and return a list of dict records."""
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        return list(reader)


def parse_list_field(value, sep=','):
    """Convert 'a,b,c' into ['a','b','c']."""
    if not value or value == 'NA':
        return []
    return [v.strip() for v in value.split(sep) if v.strip()]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data_dir', default='data', help='Directory with CSV files')
    parser.add_argument('--output', default='viz_data.json', help='Combined output JSON')
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    output = {}

    # Scenes
    scenes_path = data_dir / 'scenes.csv'
    if scenes_path.exists():
        scenes = csv_to_records(scenes_path)
        for s in scenes:
            s['characters_present'] = parse_list_field(s.get('characters_present', ''))
            s['key_objects'] = parse_list_field(s.get('key_objects', ''))
            for k in ('duration_sec', 'chronological_order'):
                if k in s and s[k] not in ('NA', ''):
                    try:
                        s[k] = int(s[k])
                    except ValueError:
                        pass
        output['scenes'] = scenes
        print(f"Loaded {len(scenes)} scenes")

    # Characters
    characters_path = data_dir / 'characters.csv'
    if characters_path.exists():
        characters = csv_to_records(characters_path)
        output['characters'] = characters
        print(f"Loaded {len(characters)} characters")

    # Symbols
    symbols_path = data_dir / 'symbols.csv'
    if symbols_path.exists():
        symbols = csv_to_records(symbols_path)
        for s in symbols:
            s['scenes_appearing'] = parse_list_field(s.get('scenes_appearing', ''))
            try:
                s['total_appearances'] = int(s['total_appearances'])
            except (KeyError, ValueError):
                pass
        output['symbols'] = symbols
        print(f"Loaded {len(symbols)} symbols")

    # Timeline mapping
    timeline_path = data_dir / 'timeline_mapping.csv'
    if timeline_path.exists():
        output['timeline'] = csv_to_records(timeline_path)
        print(f"Loaded timeline mapping")

    # Colors (optional - generated by extract_colors.py)
    colors_path = data_dir / 'colors.csv'
    if colors_path.exists():
        colors = csv_to_records(colors_path)
        # Keep only essential fields to keep file size small
        compact = []
        for c in colors:
            compact.append({
                't': float(c.get('timestamp_sec', 0)),
                'hex': c.get('dominant_color_hex', '#000000'),
                'b': float(c.get('brightness_0_255', 0)),
                's': float(c.get('saturation_0_1', 0)),
            })
        output['colors'] = compact
        print(f"Loaded {len(compact)} color samples")

    # Dialogue (optional)
    dialogue_path = data_dir / 'dialogue.csv'
    if dialogue_path.exists():
        dialogue = csv_to_records(dialogue_path)
        output['dialogue'] = dialogue
        print(f"Loaded {len(dialogue)} dialogue lines")

    # Per-shot Cinemetrics data (optional - generated by scrape_cinemetrics.py)
    shots_per_shot_path = data_dir / 'shots_per_shot.csv'
    if shots_per_shot_path.exists():
        shots_per_shot = csv_to_records(shots_per_shot_path)
        compact_shots = []
        for s in shots_per_shot:
            compact_shots.append({
                'id': s.get('shot_id', ''),
                'ds': s.get('dataset', ''),
                'type': s.get('type_name', ''),
                'color': s.get('type_color', ''),
                't': float(s.get('timestamp_sec') or 0),
                'len': float(s.get('shot_length_sec') or 0),
            })
        output['shots_per_shot'] = compact_shots
        print(f"Loaded {len(compact_shots)} per-shot rows")

    # Audio analysis (optional - generated by extract_audio.py)
    audio_path = data_dir / 'audio.csv'
    if audio_path.exists():
        audio = csv_to_records(audio_path)
        compact_audio = []
        for a in audio:
            compact_audio.append({
                't': float(a.get('timestamp_sec') or 0),
                'rms': float(a.get('rms_energy') or 0),
                'silent': int(a.get('is_silent') or 0),
                'centroid': float(a.get('spectral_centroid_hz') or 0),
                'zcr': float(a.get('zero_crossing_rate') or 0),
                'scene_id': a.get('scene_id', ''),
            })
        output['audio'] = compact_audio
        print(f"Loaded {len(compact_audio)} audio windows")

    # Survey responses (optional - collected separately, see survey_questions.md)
    survey_path = data_dir / 'survey_responses.csv'
    if survey_path.exists():
        survey = csv_to_records(survey_path)
        output['survey'] = survey
        print(f"Loaded {len(survey)} survey responses")

    # Write combined JSON
    with open(args.output, 'w', encoding='utf-8') as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
    print(f"\nWrote combined JSON to {args.output}")


if __name__ == '__main__':
    main()
